language: ruby
rvm:
  - 2.1.2
before_script:
  - "export DISPLAY=:99.0"
  - 'sh -e /etc/init.d/xvfb start'
  - "psql -c 'create database kardex_test;' -U postgres"
  - 'cp config/database.example.yml config/database.yml'
  - 'RAILS_ENV=test bundle exec rake db:migrate'
  - "export BAMBOO_API_KEY=API_TOKEN RAILS_ENV=test"
  - "export BAMBOO_SUBDOMAIN=crowdint RAILS_ENV=test"
script:
  - 'RAILS_ENV=test bundle exec rake'
